# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23504f8c45831f702a6fc2a7a4e8e984c81cc2caca399aa27af4cc4ad93a364ed5f9fc08fe801e2b01d3037aafbfdc733c3361c16ace05ee0d230264e2d16c43

test:
  secret_key_base: cff69b1653a2ffd2be1f4f86aa0c8e2fa629e9d6c267a6eb5df8e3c300f0fc4d5b51b3daa63ea9daf97f0e8e056303950fb5d4267a54117dfcbba16f8eba4d4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
